export const people = [
    {
      id: 1,
      name: 'Wiktor',
      lastName: 'Wąsik',
      age: 16,
      adult: false,
    },
    {
      id: 2,
      name: 'Anna',
      lastName: 'Nowak',
      age: 25,
      adult: true,
    },
    {
      id: 3,
      name: 'Piotr',
      lastName: 'Kowalski',
      age: 32,
      adult: true,
    },
    {
      id: 4,
      name: 'Katarzyna',
      lastName: 'Wiśniewska',
      age: 42,
      adult: true,
    },
    {
      id: 5,
      name: 'Michał',
      lastName: 'Lewandowski',
      age: 18,
      adult: false,
    },
    {
      id: 6,
      name: 'Magdalena',
      lastName: 'Dąbrowska',
      age: 20,
      adult: true,
    },
    {
      id: 7,
      name: 'Tomasz',
      lastName: 'Kaczmarek',
      age: 28,
      adult: true,
    },
    {
      id: 8,
      name: 'Natalia',
      lastName: 'Zielińska',
      age: 30,
      adult: true,
    },
    {
      id: 9,
      name: 'Marcin',
      lastName: 'Szymański',
      age: 22,
      adult: false,
    },
    {
      id: 10,
      name: 'Karolina',
      lastName: 'Woźniak',
      age: 19,
      adult: true,
    },
    {
      id: 11,
      name: 'Adam',
      lastName: 'Mazurek',
      age: 38,
      adult: true,
    },
    {
      id: 12,
      name: 'Łukasz',
      lastName: 'Krawczyk',
      age: 26,
      adult: false,
    },
    {
      id: 13,
      name: 'Marta',
      lastName: 'Piotrowska',
      age: 24,
      adult: true,
    },
    {
      id: 14,
      name: 'Dominik',
      lastName: 'Grabowski',
      age: 29,
      adult: false,
    },
    {
      id: 15,
      name: 'Aleksandra',
      lastName: 'Pawlak',
      age: 31,
      adult: true,
    },
  ];
  